### ISSUE TITLE
Intergration Stopped working

### ISSUE THREAD

**Issue by berre011** [timvancann/homeassistant-growatt#8]
So I removed it completely and reinstalled through HACS and the intergration. Now no sensors are found. I know that I am using the right username and password.
Version is the latest 003
this is what's in the log
Logger: homeassistant.components.sensor
Source: components/growatt_server/sensor.py:870
Integration: Sensor (documentation, issues)
First occurred: 10:25:48 (1 occurrences)
Last logged: 10:25:48

Error while setting up growatt_server platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/src/homeassistant/homeassistant/components/growatt_server/sensor.py", line 885, in async_setup_entry
    devices, plant_id = await hass.async_add_executor_job(get_device_list, api, config)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/growatt_server/sensor.py", line 870, in get_device_list
    devices = api.device_list(plant_id)
  File "/usr/local/lib/python3.9/site-packages/growattServer/__init__.py", line 440, in device_list
    return self.plant_info(plant_id)['deviceList']
  File "/usr/local/lib/python3.9/site-packages/growattServer/__init__.py", line 453, in plant_info
    data = json.loads(response.content.decode('utf-8'))
  File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 7 column 1 (char 19)

**Comment by Didou30** [comment]
Problème identique pour moi avec les mêmes test

**Comment by ruudvddries** [comment]
I have the same issue. It seems to be related to this -> https://github.com/indykoning/PyPi_GrowattServer/pull/18

But I have no clue on how to adapt the code to this change
