### ISSUE TITLE
Plus de remonté de données

### ISSUE THREAD

**Issue by Didou30** [timvancann/homeassistant-growatt#9]
Bonjour, depuis hier l'intégration ne remonte rien j'ai supprimé et installé mais tjrs rien ?

Avez vous ce problème ? sur le site growatt tout est correct

Merci de vos réponses

Didier

**Comment by Didou30** [comment]
Voici une partie du log en erreur:
Error while setting up growatt_server platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/src/homeassistant/homeassistant/components/growatt_server/sensor.py", line 885, in async_setup_entry
    devices, plant_id = await hass.async_add_executor_job(get_device_list, api, config)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/growatt_server/sensor.py", line 870, in get_device_list
    devices = api.device_list(plant_id)
  File "/usr/local/lib/python3.9/site-packages/growattServer/__init__.py", line 440, in device_list
    return self.plant_info(plant_id)['deviceList']
  File "/usr/local/lib/python3.9/site-packages/growattServer/__init__.py", line 453, in plant_info
    data = json.loads(response.content.decode('utf-8'))
  File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting
